name: Nightly Breakage Test

on:
  repository_dispatch:
    types: [shared-docker-linux-builders-updated]

jobs:
  linux-release-vs-ponyc-main:
    name: Verify in release mode on Linux with most recent ponyc
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Test with the most recent ponyc
        run: make test plugin config=release

  linux-debug-vs-ponyc-main:
    name: Verify in debug mode on Linux with most recent ponyc
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Test with the most recent ponyc
        run: make test plugin config=debug
