name: Changelog Bot

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - CHANGELOG.md

jobs:
  changelog-bot:
    runs-on: ubuntu-latest
    name: Update CHANGELOG.md
    steps:
      - name: Update Changelog
        uses: docker://ponylang/changelog-bot-action:0.3.4
        with:
          git_user_name: "Borja o'Cook"
          git_user_email: "ergl@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
