name: PR

on: pull_request

jobs:
  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Verify CHANGELOG
        run: changelog-tool verify
